version: '3.8'
services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_api_key_here}
      - KMP_DUPLICATE_LIB_OK=TRUE
    volumes:
      - .:/app  