name: resume-screener
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24.3
  - pytorch=2.0.1
  - sentence-transformers=2.2.2
  - openai=1.0.0
  - pymupdf=1.23.0
  - python-docx=0.8.11
  - pip=23.3.1
  - pip:
    - streamlit>=1.32.0
    - pybind11>=2.12.0