services:
  - type: web
    name: resume-screener
    runtime: docker  
    plan: free     
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/main.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PORT
        value: 8501
      - key: OPENAI_API_KEY
        fromDatabase: false  
      - key: KMP_DUPLICATE_LIB_OK
        value: "TRUE"
    healthCheckPath: /_stcore/health
